import { CreateAccount, Title } from "@/components/auth/createAccount";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Account - GoScout.me",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main className="flex items-center justify-center flex-col space-y-3 min-h-[calc(100vh-116px)]">
      <Title>Create an Account</Title>
      <CreateAccount />
    </main>
  );
}
