import { CreateAccount } from "@/components/auth/createAccount";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Account - GoScout.me",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main className="">
      <CreateAccount />
    </main>
  );
}
