import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login - GoScout.me",
  description: "Generated by create next app",
};

export default function Page() {
  return <div>aaaaa</div>;
}
