import { Athletes } from "@/components/athletes";
import { Title } from "@/components/auth/createAccount";
import { AthleteCard } from "@/components/cards/athlete";
import { ChooseSport } from "@/components/sports";
import { Filter } from "@/components/filter";
import { SearchInput } from "@/components/inputs/searchInput";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "GoScout.me",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main className="flex  min-h-[calc(100vh-116px)] ml-14">
      <Athletes />
      <Filter />
    </main>
  );
}
