import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About us - GoScout.me",
  description: "Generated by create next app",
};

export default function Aboutus() {
  return <div>aaaaa</div>;
}
