import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reach Out to Us - GoScout.me",
  description: "Generated by create next app",
};

export default function Aboutus() {
  return <div>There is nothing here!</div>;
}
