import { Title } from "@/components/auth/createAccount";
import { SignUpHeader } from "@/components/auth/signUp";
import { SignUpForm } from "@/components/form/signUp";
import { TitleTypes } from "@/types/title";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Sign Up - GoScout.me",
  description: "Generated by create next app",
};

const title: TitleTypes = {
  bold: { athlete: "Athlete Sign up ", scout: "Scout Sign up" },
  thin: {
    athlete: "and get Discovered",
    scout: "and find your next Superstar Athlete",
  },
};

export default function Page() {
  return (
    <main className="flex items-center justify-center flex-col space-y-10 min-h-[calc(100vh-116px)] pb-10">
      <SignUpHeader title={title} />
      <SignUpForm />
      <span className="text-sm max-xs:text-xs ">
        Already have an account?{" "}
        <Link href={"/auth/login"} className="underline">
          Login
        </Link>
      </span>
    </main>
  );
}
