import { UploadVideo } from "@/components/athletes/profile/video/uploadVideo";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Upload Video - GoScout.me",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main className="flex items-center justify-center flex-col space-y-10 min-h-[calc(100vh-116px)] pb-10">
      <UploadVideo />
    </main>
  );
}
