import { SignUpForm } from "@/components/form/signUp";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign Up - GoScout.me",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main className="flex items-center flex-col space-y-10">
      <span className="text-subtitle font-lexenda_deca text-3xl font-extralight">
        <span className="text-primary font-black">Scout Sign up</span> and find
        your next Superstar Athlete{" "}
      </span>
      <SignUpForm />
    </main>
  );
}
