import { Athletes } from "@/components/athletes";
import { Filter } from "@/components/filter";
import { Messages } from "@/components/messages";
import { MessagesHeader } from "@/components/messages/header";
import { Meetings } from "@/components/messages/meetings";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "GoScout.me",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main className="flex flex-col space-y-7 min-h-[calc(100vh-116px)]">
      <MessagesHeader />
      <div className="flex space-x-16">
        <Messages />
        <Meetings />
      </div>
    </main>
  );
}
