import React from "react";
import { Metadata } from "next";
import { AthleteHeader } from "@/components/header/athleteHeader";

type Props = { children: React.ReactNode };

export const metadata: Metadata = {
  title: "GoScout.me",
  description: "Generated by create next app",
};

const Layout = (props: Props) => {
  return (
    <div className="max-w-screen-xl mx-auto min-h-screen px-10">
      <AthleteHeader />
      {props.children}
    </div>
  );
};

export default Layout;
