import { SignUpHeader } from "@/components/auth/signUp";
import { RegistrationForm } from "@/components/form/registration";
import { TitleTypes } from "@/types/title";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Sign Up - GoScout.me",
  description: "Generated by create next app",
};

const title: TitleTypes = {
  bold: { athlete: "Soccer Athlete", scout: "Scout" },
  thin: { athlete: "Registration Form", scout: "Registration Form" },
};

export default function Page() {
  return (
    <main className="flex items-center justify-center flex-col space-y-10 min-h-[calc(100vh-116px)] pb-10">
      <SignUpHeader title={title} />
      <RegistrationForm />
      <span className="text-sm">
        Already have an account?{" "}
        <Link href={"/auth/login"} className="underline">
          Login
        </Link>
      </span>
    </main>
  );
}
