import { Metadata } from "next";

export const metadata: Metadata = {
  title: "GoScout.me",
  description: "Generated by create next app",
};

export default function Home() {
  return <div>aaaaa</div>;
}
