import ReachOutToUs from "@/components/react-out-to-us";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reach Out to Us - GoScout.me",
  description: "Generated by create next app",
};

export default function ReachOutToUsPage() {
  return <ReachOutToUs />;
}
